# If you’d like to deploy this to GitHub pages, rename this
# file to `gh-pages.yml` and read the mini-tutorial on
# https://www.11ty.dev/docs/deployment/#deploy-an-eleventy-project-to-github-pages
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 0 0,3,6 *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ secrets.actions_repo_token }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    permissions:
      contents: write
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v4
        with:
          repository: thatrandybrown/notes
          token: ${{ env.GITHUB_TOKEN }}
          sparse-checkout: |
            notes
          sparse-checkout-cone-mode: false
          path: new_notes
      - run: cp -r new_notes/notes/* content/notes/
      - run: ls -la new_notes/notes
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
      - name: Cache Eleventy .cache
        uses: actions/cache@v3
        with:
          path: ./.cache
          key: ${{ runner.os }}-eleventy-fetch-cache
      - run: yarn install --frozen-lockfile
      - run: yarn run build-ghpages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
