# If you’d like to deploy this to GitHub pages, rename this
# file to `gh-pages.yml` and read the mini-tutorial on
# https://www.11ty.dev/docs/deployment/#deploy-an-eleventy-project-to-github-pages
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0,3'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ secrets.actions_repo_token }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    permissions:
      contents: write
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
      - uses: actions/checkout@v3
      - name: Download the latest release
        uses: robinraju/release-downloader@v1
        continue-on-error: true
        with:
          repository: thatrandybrown/notes
          latest: true
          fileName: 'notes.zip'
          extract: true
          out-file-path: 'published_notes'
          token: ${{ env.GITHUB_TOKEN }}
      - name: Look for published notes
        run: ls -al . && ls -al published_notes && ls -al published_notes/notes
      - name: Move notes up on level in published_notes
        run: |
          mkdir -p published_notes/notes
          mv published_notes/notes/* published_notes/
          rm -rf published_notes/notes*
          ls -al published_notes
      - uses: actions/checkout@v4
        with:
          repository: thatrandybrown/notes
          token: ${{ env.GITHUB_TOKEN }}
          sparse-checkout: |
            notes
          sparse-checkout-cone-mode: false
          path: new_notes
      - run: cp -r published_notes/* content/notes/
      - run: ls -la new_notes/notes
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
      - name: Cache Eleventy .cache
        uses: actions/cache@v3
        with:
          path: ./.cache
          key: ${{ runner.os }}-eleventy-fetch-cache
      - run: yarn install --frozen-lockfile
      - run: yarn run build-ghpages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
